### ISSUE TITLE
Create a stack through a compose file

### ISSUE THREAD

**Issue by anshupitlia** [docker/stacks#63]
I want to use the api to create a stack using docker compose file. 

Basically trying to achieve through golang application `docker stack deploy --config-file docker-compose.yml stackdemo` passing in the authorization token. 

I see https://github.com/docker/stacks/pull/21/files was merged and had something related to read and convert the compose file to spec necessary for stack. But that code is no longer there. 

Why was it removed? 

How can achieve creation of a stack using docker compose file.

**Comment by justincormack** [comment]
Hi, this is not the docker stack repo, this is some old experimental code.
