### ISSUE TITLE
failed to find a Stack API version

### ISSUE THREAD

**Issue by cclauss** [docker/stacks#64]
https://github.com/docker/for-mac/issues/4966

Related to #63

**Comment by cclauss** [comment]
@dhiltgen @dperny @alexmavr @thaJeztah can you please weigh in on this one?

**Comment by justincormack** [comment]
Hi, this is not the docker stack repo, this is some old experimental code.

**Comment by cclauss** [comment]
Thx.  Where is the docker stack repo?
